name: house_prices_project
version: '1.0'
config-version: 2

profile: default

model-paths: ["models"]
seed-paths: ["data"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  house_prices_project:
    +materialized: view  # Default materialization
    example_models:
      +materialized: table