services:
  postgres:
    image: postgres:15
    container_name: dbt_postgres
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: dbt_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.6
    container_name: dbt_cli
    depends_on:
      - postgres
    environment:
      DBT_PROFILES_DIR: /usr/app
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    entrypoint: ["/bin/bash"]
    command: -c "sleep 10 && dbt debug && dbt seed && tail -f /dev/null"

volumes:
  pg_data: